/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GeneratePdfRouteImport } from './routes/generate-pdf'
import { Route as AgentInfoRouteImport } from './routes/agent-info'
import { Route as IndexRouteImport } from './routes/index'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratePdfRoute = GeneratePdfRouteImport.update({
  id: '/generate-pdf',
  path: '/generate-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentInfoRoute = AgentInfoRouteImport.update({
  id: '/agent-info',
  path: '/agent-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-info': typeof AgentInfoRoute
  '/generate-pdf': typeof GeneratePdfRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-info': typeof AgentInfoRoute
  '/generate-pdf': typeof GeneratePdfRoute
  '/home': typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-info': typeof AgentInfoRoute
  '/generate-pdf': typeof GeneratePdfRoute
  '/home': typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agent-info' | '/generate-pdf' | '/home'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agent-info' | '/generate-pdf' | '/home'
  id: '__root__' | '/' | '/agent-info' | '/generate-pdf' | '/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentInfoRoute: typeof AgentInfoRoute
  GeneratePdfRoute: typeof GeneratePdfRoute
  HomeRoute: typeof HomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-pdf': {
      id: '/generate-pdf'
      path: '/generate-pdf'
      fullPath: '/generate-pdf'
      preLoaderRoute: typeof GeneratePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-info': {
      id: '/agent-info'
      path: '/agent-info'
      fullPath: '/agent-info'
      preLoaderRoute: typeof AgentInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentInfoRoute: AgentInfoRoute,
  GeneratePdfRoute: GeneratePdfRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
